# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [20]:
import pandas as pd

df1 = pd.read_csv("../../Day_2/lab-dw-data-cleaning-and-formatting/cleaned_df.csv")
display(df1)
url = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv"
url1 = "https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv"
df2 = pd.read_csv(url)
df3 = pd.read_csv(url1)
display(df2)
display(df3)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,793690,0,1000,0,Personal Auto,Four-Door Car,2
1,QZ44356,Arizona,F,Bachelor,697953,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,F,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,M,Bachelor,764586,0,106,0,Corporate Auto,SUV,529
4,GA49547,Washington,M,High School or Below,536307,36357,68,0,Personal Auto,Four-Door Car,17
...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,305955,38644,78,1,Personal Auto,Four-Door Car,361
1067,VJ51327,California,F,High School or Below,2031499,63209,102,2,Personal Auto,SUV,207
1068,GS98873,Arizona,F,Bachelor,323912,16061,88,0,Personal Auto,Four-Door Car,633
1069,CW49887,California,F,Master,462680,79487,114,0,Special Auto,SUV,547
1070,MY31220,California,F,College,899704,54230,112,0,Personal Auto,Two-Door Car,537

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.600000,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.200000,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.600000,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.200000,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.200000,Corporate Auto,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...
991,HV85198,Arizona,M,Master,847141.75%,63513,70,1/0/00,185.667213,Personal Auto,Four-Door Car
992,BS91566,Arizona,F,College,543121.91%,58161,68,1/0/00,140.747286,Corporate Auto,Four-Door Car
993,IL40123,Nevada,F,College,568964.41%,83640,70,1/0/00,471.050488,Corporate Auto,Two-Door Car
994,MY32149,California,F,Master,368672.38%,0,96,1/0/00,28.460568,Personal Auto,Two-Door Car
995,SA91515,California,M,Bachelor,399258.39%,0,111,1/0/00,700.349052,Personal Auto,SUV

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV
...,...,...,...,...,...,...,...,...,...,...,...
7065,LA72316,California,23405.987980,Bachelor,M,71941,73,0,Personal Auto,198.234764,Four-Door Car
7066,PK87824,California,3096.511217,College,F,21604,79,0,Corporate Auto,379.200000,Four-Door Car
7067,TD14365,California,8163.890428,Bachelor,M,0,85,3,Corporate Auto,790.784983,Four-Door Car
7068,UP19263,California,7524.442436,College,M,21941,96,0,Personal Auto,691.200000,Four-Door Car
7069,Y167826,California,2611.836866,College,M,0,77,0,Corporate Auto,369.600000,Two-Door Car

In [21]:
df2.columns = (
            df2.columns.
            str.replace("ST","state").
            str.strip().
            str.lower().
            str.replace(" ","_")
            )
df3.columns = (
            df3.columns.
            str.strip().
            str.lower().
            str.replace(" ","_")
            )
print("\n Cleaned columns df1: ", df1.columns.tolist())    
print("\n Cleaned columns df2: ", df2.columns.tolist()) 
print("\n Cleaned columns df3: ", df3.columns.tolist()) 

cols = df1.columns.tolist()
df2 = df2[cols]
df3 = df2[cols]

print(df1.columns.tolist() == df2.columns.tolist() == df3.columns.tolist())

 Cleaned columns df1:  ['customer', 'state', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'vehicle_class', 'total_claim_amount']

 Cleaned columns df2:  ['customer', 'state', 'gender', 'education', 'customer_lifetime_value', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'total_claim_amount', 'policy_type', 'vehicle_class']

 Cleaned columns df3:  ['customer', 'state', 'customer_lifetime_value', 'education', 'gender', 'income', 'monthly_premium_auto', 'number_of_open_complaints', 'policy_type', 'total_claim_amount', 'vehicle_class']
True

In [22]:
display(df2.head(10))
#display(df2["gender"].unique().tolist()))
gender_standard = {
    "F" : "F",
    "M" : "M",
    "female" : "F",
    "Male": "M"    
}
df2["gender"] = df2["gender"].map(gender_standard)
display(df2["gender"].unique().tolist())
#display(df2["education"].unique().tolist()))
df2["education"] = df2["education"].str.replace("Bachelors","Bachelor")
display(df2["education"].unique().tolist())
df2["customer_lifetime_value"] = df2["customer_lifetime_value"].str.replace("%","",regex=False)
#display(df2["state"].unique().tolist()))
df2["state"]=df2["state"].replace("AZ","Arizona")
display(df2["state"].unique().tolist())


display(df2["vehicle_class"].unique().tolist())
vehicle = {
            "Sports Car" : "Luxury",
            "Luxury SUV" : "Luxury",
            "Luxury Car" : "Luxury"
            }  
df2["vehicle_class"] =df2["vehicle_class"].replace(vehicle)
print("After mapping:", df2["vehicle_class"].unique().tolist())

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,Personal Auto,Four-Door Car,633.600000
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,Special Auto,SUV,547.200000
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,Personal Auto,Two-Door Car,537.600000
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,Personal Auto,Luxury Car,1027.200000
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,Corporate Auto,Two-Door Car,451.200000
5,WL99637,Arizona,M,Bachelor,761413.80%,27293,96,1/0/00,Personal Auto,Two-Door Car,469.030907
6,UC84059,California,F,Master,689845.53%,70950,171,1/0/00,Personal Auto,Sports Car,565.929394
7,HW62747,Oregon,M,College,229837.92%,0,63,1/0/00,Corporate Auto,Four-Door Car,302.400000
8,BH11344,Oregon,F,Doctor,280669.61%,37009,71,1/0/00,Corporate Auto,Two-Door Car,145.673348
9,TX28465,Nevada,M,College,520611.82%,52629,65,1/0/00,Personal Auto,Four-Door Car,136.684141

['F', 'M', nan]

['Bachelor', 'Master', 'College', 'Doctor', 'High School or Below']

['Arizona', 'California', 'Oregon', 'Nevada', 'Washington']

['Four-Door Car',
 'SUV',
 'Two-Door Car',
 'Luxury Car',
 'Sports Car',
 'Luxury SUV']

After mapping: ['Four-Door Car', 'SUV', 'Two-Door Car', 'Luxury']

In [23]:
display(df3.head())
display(df2["gender"].unique().tolist())
display(df2["education"].unique().tolist())
df3["customer_lifetime_value"] = df3["customer_lifetime_value"].str.replace("%","",regex=False)
display(df2["state"].unique().tolist())
display(df2["vehicle_class"].unique().tolist())

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,Personal Auto,Four-Door Car,633.6
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,Special Auto,SUV,547.2
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,Personal Auto,Two-Door Car,537.6
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,Personal Auto,Luxury Car,1027.2
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,Corporate Auto,Two-Door Car,451.2

['F', 'M', nan]

['Bachelor', 'Master', 'College', 'Doctor', 'High School or Below']

['Arizona', 'California', 'Oregon', 'Nevada', 'Washington']

['Four-Door Car', 'SUV', 'Two-Door Car', 'Luxury']

In [24]:
#df2["number_of_open_complaints"] = df2["number_of_open_complaints"].str.split("/").str[1]
display(df1.dtypes)
display(df2.dtypes)
display(df2["customer_lifetime_value"].isna().sum())

df2["customer_lifetime_value"] = pd.to_numeric(df2["customer_lifetime_value"], errors="coerce")
df2["customer_lifetime_value"] =df2["customer_lifetime_value"].fillna(df2["customer_lifetime_value"].mean())
df2["customer_lifetime_value"] = df2["customer_lifetime_value"].astype("int64")

display(df3.dtypes)
display(df3["customer_lifetime_value"].isna().sum())

df3["customer_lifetime_value"] = pd.to_numeric(df3["customer_lifetime_value"], errors="coerce")
df3["customer_lifetime_value"] =df3["customer_lifetime_value"].fillna(df3["customer_lifetime_value"].mean())
df3["customer_lifetime_value"] = df3["customer_lifetime_value"].astype("int64")

customer                       str
state                          str
gender                         str
education                      str
customer_lifetime_value      int64
income                       int64
monthly_premium_auto         int64
number_of_open_complaints    int64
policy_type                    str
vehicle_class                  str
total_claim_amount           int64
dtype: object

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value          str
income                         int64
monthly_premium_auto           int64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

np.int64(4)

customer                         str
state                            str
gender                           str
education                        str
customer_lifetime_value          str
income                         int64
monthly_premium_auto           int64
number_of_open_complaints        str
policy_type                      str
vehicle_class                    str
total_claim_amount           float64
dtype: object

np.int64(4)

In [25]:
display(df2["number_of_open_complaints"].isna().sum())
df2["number_of_open_complaints"]=df2["number_of_open_complaints"].str.split("/").str[1]
df2["number_of_open_complaints"] = df2["number_of_open_complaints"].astype(int)
display(df2["number_of_open_complaints"].head())


display(df3["number_of_open_complaints"].isna().sum())
df3["number_of_open_complaints"]=df3["number_of_open_complaints"].str.split("/").str[1]
df3["number_of_open_complaints"] = df3["number_of_open_complaints"].astype(int)
display(df3["number_of_open_complaints"].head())

np.int64(0)

0    0
1    0
2    0
3    1
4    0
Name: number_of_open_complaints, dtype: int64

np.int64(0)

0    0
1    0
2    0
3    1
4    0
Name: number_of_open_complaints, dtype: int64

In [26]:
display(df2.isna().sum())
df2["gender"] = df2["gender"].fillna(df2["gender"].mode()[0])
display(df3.isna().sum())
df3["gender"] = df3["gender"].fillna(df3["gender"].mode()[0])

customer                     0
state                        0
gender                       5
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

customer                     0
state                        0
gender                       5
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [27]:
df2["total_claim_amount"] =df2["total_claim_amount"].astype(int)
display(df2.isna().sum())

df3["total_claim_amount"] =df3["total_claim_amount"].astype(int)
display(df2.isna().sum())

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

customer                     0
state                        0
gender                       0
education                    0
customer_lifetime_value      0
income                       0
monthly_premium_auto         0
number_of_open_complaints    0
policy_type                  0
vehicle_class                0
total_claim_amount           0
dtype: int64

In [28]:
display(df2["customer"].duplicated().sum())
display(df3["customer"].duplicated().sum())
df2["customer"].reset_index(drop=True)
df3["customer"].reset_index(drop=True)

np.int64(0)

np.int64(0)

0      GS98873
1      CW49887
2      MY31220
3      UH35128
4      WH52799
        ...
991    HV85198
992    BS91566
993    IL40123
994    MY32149
995    SA91515
Name: customer, Length: 996, dtype: str

In [29]:
df4 = pd.concat([df1,df2,df3], axis=0, ignore_index=True)
display(df4)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,F,Master,793690,0,1000,0,Personal Auto,Four-Door Car,2
1,QZ44356,Arizona,F,Bachelor,697953,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,F,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,M,Bachelor,764586,0,106,0,Corporate Auto,SUV,529
4,GA49547,Washington,M,High School or Below,536307,36357,68,0,Personal Auto,Four-Door Car,17
...,...,...,...,...,...,...,...,...,...,...,...
3058,HV85198,Arizona,M,Master,847141,63513,70,0,Personal Auto,Four-Door Car,185
3059,BS91566,Arizona,F,College,543121,58161,68,0,Corporate Auto,Four-Door Car,140
3060,IL40123,Nevada,F,College,568964,83640,70,0,Corporate Auto,Two-Door Car,471
3061,MY32149,California,F,Master,368672,0,96,0,Personal Auto,Two-Door Car,28
3062,SA91515,California,M,Bachelor,399258,0,111,0,Personal Auto,SUV,700

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [31]:

df_mca = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")
display(df_mca.head())
display(df_mca.info())
df_mca =df_mca .drop(columns = ["unnamed:_0"])
df_mca["customer_lifetime_value"]=df_mca["customer_lifetime_value"].astype(int)
df_mca["number_of_open_complaints"]=df_mca["number_of_open_complaints"].astype(int)
df_mca["months_since_last_claim"]=df_mca["months_since_last_claim"].astype(int)
df_mca["total_claim_amount"]=df_mca["total_claim_amount"].astype(int)
display(df_mca.info())

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

<class 'pandas.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  str
 2   state                          10910 non-null  str
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  str
 5   coverage                       10910 non-null  str
 6   education                      10910 non-null  str
 7   effective_to_date              10910 non-null  str
 8   employmentstatus               10910 non-null  str
 9   gender                         10910 non-null  str
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  str
 12  marital_status                 10910 non-null  str
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  str
 19  policy                         10910 non-null  str
 20  renew_offer_type               10910 non-null  str
 21  sales_channel                  10910 non-null  str
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  str
 24  vehicle_size                   10910 non-null  str
 25  vehicle_type                   10910 non-null  str
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), str(17)
memory usage: 3.5 MB

None

<class 'pandas.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 26 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer                       10910 non-null  str
 1   state                          10910 non-null  str
 2   customer_lifetime_value        10910 non-null  int64
 3   response                       10910 non-null  str
 4   coverage                       10910 non-null  str
 5   education                      10910 non-null  str
 6   effective_to_date              10910 non-null  str
 7   employmentstatus               10910 non-null  str
 8   gender                         10910 non-null  str
 9   income                         10910 non-null  int64
 10  location_code                  10910 non-null  str
 11  marital_status                 10910 non-null  str
 12  monthly_premium_auto           10910 non-null  int64
 13  months_since_last_claim        10910 non-null  int64
 14  months_since_policy_inception  10910 non-null  int64
 15  number_of_open_complaints      10910 non-null  int64
 16  number_of_policies             10910 non-null  int64
 17  policy_type                    10910 non-null  str
 18  policy                         10910 non-null  str
 19  renew_offer_type               10910 non-null  str
 20  sales_channel                  10910 non-null  str
 21  total_claim_amount             10910 non-null  int64
 22  vehicle_class                  10910 non-null  str
 23  vehicle_size                   10910 non-null  str
 24  vehicle_type                   10910 non-null  str
 25  month                          10910 non-null  int64
dtypes: int64(9), str(17)
memory usage: 3.4 MB

None

In [32]:
display(df_mca.head())

sales_summary = df_mca.pivot_table(
                index = "sales_channel",
                values = "total_claim_amount",
                aggfunc = "sum"
                )
display(sales_summary.round(2))
#sales_channel- Agent has brought the most sales in terms of revenue

,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,income,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,DK49336,Arizona,4809,No,Basic,College,2011-02-18,Employed,M,48029,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292,Four-Door Car,Medsize,A,2
1,KX64629,California,2228,No,Basic,College,2011-01-18,Unemployed,F,0,...,1,Personal Auto,Personal L3,Offer4,Call Center,744,Four-Door Car,Medsize,A,1
2,LZ68649,Washington,14947,No,Basic,Bachelor,2011-02-10,Employed,M,22139,...,2,Personal Auto,Personal L3,Offer3,Call Center,480,SUV,Medsize,A,2
3,XL78013,Oregon,22332,Yes,Extended,College,2011-01-11,Employed,M,49078,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484,Four-Door Car,Medsize,A,1
4,QA50777,Oregon,9025,No,Premium,Bachelor,2011-01-17,Medical Leave,F,23675,...,7,Personal Auto,Personal L2,Offer1,Branch,707,Four-Door Car,Medsize,A,1

               total_claim_amount
sales_channel
Agent                     1808338
Branch                    1299802
Call Center                925591
Web                        705818

In [33]:
cust_life_summary = df_mca.pivot_table(
            index = "education",
            columns = "gender",
            values = "customer_lifetime_value",
            aggfunc = "mean"
            )
print("Average Customer life value based on eduaction and gender \n",cust_life_summary.round(2) )

Average Customer life value based on eduaction and gender
 gender                      F        M
education
Bachelor              7873.79  7703.09
College               7748.31  8051.94
Doctor                7328.00  7414.85
High School or Below  8674.72  8149.19
Master                8156.54  8168.33

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here